version: "3"

services:
  webassembly:
    build: 
      context: ./dockerfile
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    container_name: webassemblyTutorial01
    command: sleep infinity